/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.airport;

import client.form.flight.*;
import client.form.tickets.*;
import client.communication.Communication;
import client.controller.ControllerDeleteAirport;
import client.controller.ControllerDeletePilot;
import client.controller.ControllerFindAllAirports;
import client.controller.ControllerFindSpecificAirport;
import client.forme.OpstaEkranskaForma;
import domen.Aerodrom;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Božidar
 */
public class FindAirportForm extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private final ControllerFindAllAirports contFindAllAirports;
    private final ControllerFindSpecificAirport contFindSpecificAirport;
    private final ControllerDeleteAirport contDeleteAirport;

    /**
     * Creates new form CreateTicketForm
     */
    public FindAirportForm() {
        initComponents();
        contFindAllAirports = new ControllerFindAllAirports(this);
        contFindSpecificAirport = new ControllerFindSpecificAirport(this);
        contDeleteAirport = new ControllerDeleteAirport(this);
        prepareForm();
        contFindAllAirports.prepareTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelFullTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirports = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanelFilter = new javax.swing.JPanel();
        rbCity = new javax.swing.JRadioButton();
        txtCity = new javax.swing.JTextField();
        rbCountry = new javax.swing.JRadioButton();
        txtCountry = new javax.swing.JTextField();
        rbAirportID = new javax.swing.JRadioButton();
        txtAirportID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addGap(370, 370, 370))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblNewTicket.setText("Airport");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewTicket)
                .addGap(426, 426, 426))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Airports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(236, 183, 83))); // NOI18N

        jPanelFullTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Airports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(243, 187, 87))); // NOI18N

        tblAirports.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        tblAirports.setForeground(new java.awt.Color(255, 255, 255));
        tblAirports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airport ID", "Name", "City", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAirports.setRowHeight(35);
        jScrollPane1.setViewportView(tblAirports);
        if (tblAirports.getColumnModel().getColumnCount() > 0) {
            tblAirports.getColumnModel().getColumn(0).setResizable(false);
            tblAirports.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAirports.getColumnModel().getColumn(1).setResizable(false);
            tblAirports.getColumnModel().getColumn(2).setResizable(false);
            tblAirports.getColumnModel().getColumn(3).setResizable(false);
        }

        btnCreate.setText("ADD NEW");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("SHOW ALL");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 183, 83));
        jLabel1.setText("*Selected");

        lblStatus.setBackground(new java.awt.Color(153, 255, 153));
        lblStatus.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblStatus.setText("  ");

        javax.swing.GroupLayout jPanelFullTicketLayout = new javax.swing.GroupLayout(jPanelFullTicket);
        jPanelFullTicket.setLayout(jPanelFullTicketLayout);
        jPanelFullTicketLayout.setHorizontalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanelFullTicketLayout.setVerticalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnUpdate)
                        .addGap(94, 94, 94)
                        .addComponent(btnCreate)
                        .addGap(30, 30, 30)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanelFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Specific search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        rbCity.setBackground(new java.awt.Color(0, 94, 145));
        rbCity.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbCity.setForeground(new java.awt.Color(236, 183, 83));
        rbCity.setText("City");
        rbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCityActionPerformed(evt);
            }
        });

        txtCity.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        rbCountry.setBackground(new java.awt.Color(0, 94, 145));
        rbCountry.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbCountry.setForeground(new java.awt.Color(236, 183, 83));
        rbCountry.setText("Country");
        rbCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCountryActionPerformed(evt);
            }
        });

        txtCountry.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        rbAirportID.setBackground(new java.awt.Color(0, 94, 145));
        rbAirportID.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbAirportID.setForeground(new java.awt.Color(236, 183, 83));
        rbAirportID.setText("Airport ID");
        rbAirportID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAirportIDActionPerformed(evt);
            }
        });

        txtAirportID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterLayout = new javax.swing.GroupLayout(jPanelFilter);
        jPanelFilter.setLayout(jPanelFilterLayout);
        jPanelFilterLayout.setHorizontalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCity)
                    .addComponent(rbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAirportID)
                    .addComponent(rbAirportID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnFind)
                .addGap(53, 53, 53))
        );
        jPanelFilterLayout.setVerticalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFilterLayout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelFilterLayout.createSequentialGroup()
                                    .addComponent(rbCountry)
                                    .addGap(48, 48, 48)))
                            .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelFilterLayout.createSequentialGroup()
                                    .addComponent(rbCity)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelFilterLayout.createSequentialGroup()
                                    .addComponent(rbAirportID)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAirportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnFind)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
         }//GEN-LAST:event_txtCityActionPerformed

    private void rbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCityActionPerformed

        if (rbCity.isSelected()) {
            txtCity.setEnabled(true);
            txtCity.setBackground(whiteColor);
        } else {
            txtCity.setEnabled(false);
            txtCity.setBackground(blueColor);
            txtCity.setText("");
        }    }//GEN-LAST:event_rbCityActionPerformed

    private void rbCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCountryActionPerformed
        if (rbCountry.isSelected()) {
            txtCountry.setEnabled(true);
            txtCountry.setBackground(whiteColor);
        } else {
            txtCountry.setEnabled(false);
            txtCountry.setBackground(blueColor);
            txtCountry.setText("");
        }
    }//GEN-LAST:event_rbCountryActionPerformed

    private void rbAirportIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAirportIDActionPerformed
        if (rbAirportID.isSelected()) {
            txtAirportID.setEnabled(true);
            txtAirportID.setBackground(whiteColor);
        } else {
            txtAirportID.setEnabled(false);
            txtAirportID.setBackground(blueColor);
            txtAirportID.setText("");
        }
    }//GEN-LAST:event_rbAirportIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        CreateAirportForm caf = new CreateAirportForm();
        caf.setVisible(true);
        caf.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contFindAllAirports.SOLoadListAirports();
        contFindAllAirports.fillTable();
    }//GEN-LAST:event_formWindowOpened

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        contFindSpecificAirport.prepareTable();
        contFindSpecificAirport.SOFindSpecificAirports();
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!tblAirports.getSelectionModel().isSelectionEmpty()) {

            int input = JOptionPane.showConfirmDialog(null,
                    "Do you want to proceed to delete this airport?", "Select an Option...", JOptionPane.YES_NO_OPTION);

            if (input == 0) {
                contDeleteAirport.SODeleteAirport();
                contFindSpecificAirport.prepareTable();
                contFindAllAirports.SOLoadListAirports();
                contFindAllAirports.fillTable();
            } else {
                return;
            }
        } else {
            lblStatus.setForeground(Color.WHITE);
            lblStatus.setBackground(new Color(219, 31, 31));
            lblStatus.setOpaque(true);
            lblStatus.setText("You didnt select any row!");
            lblStatus.setHorizontalAlignment(SwingConstants.CENTER);
            lblStatus.setVerticalAlignment(SwingConstants.CENTER);

        }    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        contFindSpecificAirport.prepareTable();
        contFindAllAirports.SOLoadListAirports();
        contFindAllAirports.fillTable();

        lblStatus.setForeground(Color.WHITE);
        lblStatus.setBackground(new Color(75, 181, 67));
        lblStatus.setOpaque(true);
        lblStatus.setText("All airports are showed!");
        lblStatus.setHorizontalAlignment(SwingConstants.CENTER);
        lblStatus.setVerticalAlignment(SwingConstants.CENTER);    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFilter;
    private javax.swing.JPanel jPanelFullTicket;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rbAirportID;
    private javax.swing.JRadioButton rbCity;
    private javax.swing.JRadioButton rbCountry;
    private javax.swing.JTable tblAirports;
    private javax.swing.JTextField txtAirportID;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(whiteColor);
        jPanelFilter.setBackground(blueColor);
        jPanelFullTicket.setBackground(blueColor);
        lblNewTicket.setForeground(yellowColor);
        tblAirports.setBackground(whiteColor);
        tblAirports.setForeground(blueColor);

        txtAirportID.setEnabled(false);
        txtAirportID.setBackground(blueColor);
        txtAirportID.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        txtCity.setEnabled(false);
        txtCity.setBackground(blueColor);
        txtCity.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        txtCountry.setEnabled(false);
        txtCountry.setBackground(blueColor);
        txtCountry.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        prepareButton();
    }

    private void prepareButton() {

        btnCreate.setBackground(whiteColor);
        btnCreate.setForeground(blueColor);
        btnCreate.setFocusPainted(false);
        btnCreate.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnDelete.setBackground(whiteColor);
        btnDelete.setForeground(blueColor);
        btnDelete.setFocusPainted(false);
        btnDelete.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnUpdate.setBackground(whiteColor);
        btnUpdate.setForeground(blueColor);
        btnUpdate.setFocusPainted(false);
        btnUpdate.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnFind.setBackground(yellowColor);
        btnFind.setForeground(whiteColor);
        btnFind.setFocusPainted(false);
        btnFind.setFont(new Font("Sans Serif", Font.BOLD, 22));

    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Aerodrom();
    }

    @Override
    public JLabel getStatusLabel() {
        return lblStatus;
    }

    public JTable getTblAirports() {
        return tblAirports;
    }

    public JRadioButton getRbCity() {
        return rbCity;
    }

    public JRadioButton getRbCountry() {
        return rbCountry;
    }

    public JRadioButton getRbAirportID() {
        return rbAirportID;
    }

    public JTextField getTxtCity() {
        return txtCity;
    }

    public JTextField getTxtCountry() {
        return txtCountry;
    }

    public JTextField getTxtAirportID() {
        return txtAirportID;
    }

}
