/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.flight;

import client.form.tickets.*;
import client.communication.Communication;
import client.controller.ControllerCreateFlight;
import client.controller.ControllerFindAllAirports;
import client.forme.OpstaEkranskaForma;
import domen.Let;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Božidar
 */
public class CreateFlightForm extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private Let let;
    private final ControllerCreateFlight contCreateFlight;

    /**
     * Creates new form CreateTicketForm
     */
    public CreateFlightForm() {
        initComponents();
        contCreateFlight = new ControllerCreateFlight(this);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelFlight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbStartDestination = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbFinalDestination = new javax.swing.JComboBox();
        jPanelTime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelPilot = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbPilot = new javax.swing.JComboBox();
        jPanelPilot1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbAirplane = new javax.swing.JComboBox();
        btnCreateFlight = new javax.swing.JButton();
        txtIDFlight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaslovLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(lblNaslov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addContainerGap())
        );

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        lblNewTicket.setText("New Flight");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(lblNewTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel5.setText("Flight ID:");

        jPanelFlight.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Route", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(247, 184, 84))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setText("From");

        cmbStartDestination.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel6.setText("To");

        cmbFinalDestination.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelFlightLayout = new javax.swing.GroupLayout(jPanelFlight);
        jPanelFlight.setLayout(jPanelFlightLayout);
        jPanelFlightLayout.setHorizontalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStartDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cmbFinalDestination, 0, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFlightLayout.setVerticalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFlightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStartDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(cmbFinalDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelTime.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(247, 184, 84))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 94, 145));
        jLabel4.setText("Date:");

        txtDate.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 94, 145));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 186, 86));
        jLabel7.setText("Format: YYYY-MM-DD");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 94, 145));
        jLabel8.setText("Time:");

        txtTime.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtTime.setForeground(new java.awt.Color(0, 94, 145));
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 186, 86));
        jLabel10.setText("Format: HH:MM");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 94, 145));
        jLabel9.setText("Duration:");

        txtDuration.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtDuration.setForeground(new java.awt.Color(0, 94, 145));
        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(245, 186, 86));
        jLabel11.setText("Format: Minutes");

        javax.swing.GroupLayout jPanelTimeLayout = new javax.swing.GroupLayout(jPanelTime);
        jPanelTime.setLayout(jPanelTimeLayout);
        jPanelTimeLayout.setHorizontalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)))
                .addGap(36, 36, 36)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25)))
                .addGap(61, 61, 61)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(25, 25, 25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTimeLayout.setVerticalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPilot.setBackground(new java.awt.Color(0, 94, 145));
        jPanelPilot.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(244, 184, 84))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select pilot on this flight:");

        cmbPilot.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        cmbPilot.setForeground(new java.awt.Color(0, 94, 145));

        javax.swing.GroupLayout jPanelPilotLayout = new javax.swing.GroupLayout(jPanelPilot);
        jPanelPilot.setLayout(jPanelPilotLayout);
        jPanelPilotLayout.setHorizontalGroup(
            jPanelPilotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilotLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
            .addGroup(jPanelPilotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPilot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPilotLayout.setVerticalGroup(
            jPanelPilotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilotLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelPilot1.setBackground(new java.awt.Color(0, 94, 145));
        jPanelPilot1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Airplane", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(244, 184, 84))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select airplane on this flight:");

        cmbAirplane.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        cmbAirplane.setForeground(new java.awt.Color(0, 94, 145));

        javax.swing.GroupLayout jPanelPilot1Layout = new javax.swing.GroupLayout(jPanelPilot1);
        jPanelPilot1.setLayout(jPanelPilot1Layout);
        jPanelPilot1Layout.setHorizontalGroup(
            jPanelPilot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilot1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
            .addGroup(jPanelPilot1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAirplane, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPilot1Layout.setVerticalGroup(
            jPanelPilot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilot1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnCreateFlight.setText("CREATE FLIGHT");
        btnCreateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFlightActionPerformed(evt);
            }
        });

        txtIDFlight.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtIDFlight.setText("1");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDFlight)
                                .addGap(45, 45, 45))
                            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelMainLayout.createSequentialGroup()
                                    .addComponent(jPanelPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jPanelPilot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnCreateFlight)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtIDFlight))
                .addGap(33, 33, 33)
                .addComponent(jPanelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPilot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnCreateFlight)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed

    private void btnCreateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFlightActionPerformed
        contCreateFlight.SOCreateFlight();
    }//GEN-LAST:event_btnCreateFlightActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contCreateFlight.SOFindNextIDFlight();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateFlight;
    private javax.swing.JComboBox cmbAirplane;
    private javax.swing.JComboBox cmbFinalDestination;
    private javax.swing.JComboBox cmbPilot;
    private javax.swing.JComboBox<String> cmbStartDestination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelFlight;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelPilot;
    private javax.swing.JPanel jPanelPilot1;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelTime;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JLabel txtIDFlight;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(whiteColor);
        jPanelFlight.setBackground(blueColor);
        jPanelTime.setBackground(blueColor);
        lblNewTicket.setForeground(yellowColor);

        jLabel2.setForeground(whiteColor);
        jLabel4.setForeground(whiteColor);
        jLabel5.setForeground(whiteColor);
        jLabel6.setForeground(whiteColor);
        jLabel1.setForeground(whiteColor);
        jLabel8.setForeground(whiteColor);
        jLabel9.setForeground(whiteColor);

        cmbFinalDestination.setForeground(blueColor);
        cmbFinalDestination.setBackground(whiteColor);
        cmbStartDestination.setForeground(blueColor);
        cmbStartDestination.setBackground(whiteColor);

        txtDate.setForeground(blueColor);
        txtIDFlight.setForeground(whiteColor);

        contCreateFlight.pripremiKomboBox();

        prepareButton();
    }

    private void prepareButton() {

        btnCreateFlight.setBackground(whiteColor);
        btnCreateFlight.setForeground(blueColor);
        btnCreateFlight.setFocusPainted(false);
        btnCreateFlight.setFont(new Font("Sans Serif", Font.BOLD, 24));

    }

    public JLabel getTxtIDFlight() {
        return txtIDFlight;
    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Let();
    }

    @Override
    public JLabel getStatusLabel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getTxtDate() {
        return txtDate;
    }

    public JTextField getTxtTime() {
        return txtTime;
    }

    public JTextField getTxtDuration() {
        return txtDuration;
    }

    public JComboBox getCmbPilot() {
        return cmbPilot;
    }

    public JComboBox getCmbAirplane() {
        return cmbAirplane;
    }

    public JComboBox getCmbFinalDestination() {
        return cmbFinalDestination;
    }

    public JComboBox getCmbStartDestination() {
        return cmbStartDestination;
    }

}
