/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.flight;

import client.form.tickets.*;
import client.communication.Communication;
import client.controller.ControllerFindAllFlights;
import client.controller.ControllerFindSpecificFlight;
import client.forme.OpstaEkranskaForma;
import domen.Let;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Božidar
 */
public class FindFlightForm extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private final ControllerFindAllFlights contFindAllFlights;
    private final ControllerFindSpecificFlight contFindSpecificFlight;

    /**
     * Creates new form CreateTicketForm
     */
    public FindFlightForm() {
        initComponents();
        contFindAllFlights = new ControllerFindAllFlights(this);
        contFindSpecificFlight = new ControllerFindSpecificFlight(this);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelFullTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        jPanelUpdate = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jPanelFilter = new javax.swing.JPanel();
        txtTakeOff = new javax.swing.JTextField();
        rbAirportTakeOff = new javax.swing.JRadioButton();
        rbAirportLanding = new javax.swing.JRadioButton();
        txtLanding = new javax.swing.JTextField();
        rbFlightID = new javax.swing.JRadioButton();
        txtFlightID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaslovLayout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(lblNaslov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addContainerGap())
        );

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblNewTicket.setText("Flights");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(581, 581, 581)
                .addComponent(lblNewTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flights", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(236, 183, 83))); // NOI18N

        jPanelFullTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All flights", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(243, 187, 87))); // NOI18N

        tblFlights.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        tblFlights.setForeground(new java.awt.Color(255, 255, 255));
        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight", "Class", "Gate", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFlights.setRowHeight(35);
        jScrollPane1.setViewportView(tblFlights);
        if (tblFlights.getColumnModel().getColumnCount() > 0) {
            tblFlights.getColumnModel().getColumn(0).setResizable(false);
            tblFlights.getColumnModel().getColumn(1).setResizable(false);
            tblFlights.getColumnModel().getColumn(2).setResizable(false);
            tblFlights.getColumnModel().getColumn(3).setResizable(false);
        }

        lblStatus.setText(" ");

        javax.swing.GroupLayout jPanelFullTicketLayout = new javax.swing.GroupLayout(jPanelFullTicket);
        jPanelFullTicket.setLayout(jPanelFullTicketLayout);
        jPanelFullTicketLayout.setHorizontalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFullTicketLayout.setVerticalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUpdate.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblUpdate.setText("Create new flight");

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdateLayout = new javax.swing.GroupLayout(jPanelUpdate);
        jPanelUpdate.setLayout(jPanelUpdateLayout);
        jPanelUpdateLayout.setHorizontalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdateLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lblUpdate)
                .addGap(89, 89, 89)
                .addComponent(btnCreate)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanelUpdateLayout.setVerticalGroup(
            jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdate)
                    .addComponent(btnCreate))
                .addContainerGap())
        );

        jPanelFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Specific search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        txtTakeOff.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        rbAirportTakeOff.setBackground(new java.awt.Color(0, 94, 145));
        rbAirportTakeOff.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbAirportTakeOff.setForeground(new java.awt.Color(236, 183, 83));
        rbAirportTakeOff.setText("Airport Takeoff");
        rbAirportTakeOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAirportTakeOffActionPerformed(evt);
            }
        });

        rbAirportLanding.setBackground(new java.awt.Color(0, 94, 145));
        rbAirportLanding.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbAirportLanding.setForeground(new java.awt.Color(236, 183, 83));
        rbAirportLanding.setText("Airport Landing");
        rbAirportLanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAirportLandingActionPerformed(evt);
            }
        });

        txtLanding.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtLanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLandingActionPerformed(evt);
            }
        });

        rbFlightID.setBackground(new java.awt.Color(0, 94, 145));
        rbFlightID.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbFlightID.setForeground(new java.awt.Color(236, 183, 83));
        rbFlightID.setText("Flight ID");
        rbFlightID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFlightIDActionPerformed(evt);
            }
        });

        txtFlightID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterLayout = new javax.swing.GroupLayout(jPanelFilter);
        jPanelFilter.setLayout(jPanelFilterLayout);
        jPanelFilterLayout.setHorizontalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbAirportTakeOff)
                    .addComponent(txtTakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbAirportLanding)
                    .addComponent(txtLanding, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFlightID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFlightID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(btnFind)
                .addGap(70, 70, 70))
        );
        jPanelFilterLayout.setVerticalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFilterLayout.createSequentialGroup()
                                .addComponent(rbFlightID)
                                .addGap(18, 18, 18))
                            .addGroup(jPanelFilterLayout.createSequentialGroup()
                                .addComponent(btnFind)
                                .addGap(1, 1, 1)))
                        .addComponent(txtFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addComponent(rbAirportLanding)
                        .addGap(18, 18, 18)
                        .addComponent(txtLanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addComponent(rbAirportTakeOff)
                        .addGap(18, 18, 18)
                        .addComponent(txtTakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnShowAll.setText("SHOW ALL");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(btnShowAll)
                        .addGap(75, 75, 75))))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAirportTakeOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAirportTakeOffActionPerformed

        if (rbAirportTakeOff.isSelected()) {
            txtTakeOff.setEnabled(true);
            txtTakeOff.setBackground(whiteColor);
        } else {
            txtTakeOff.setEnabled(false);
            txtTakeOff.setBackground(blueColor);
            txtTakeOff.setText("");
        }

    }//GEN-LAST:event_rbAirportTakeOffActionPerformed

    private void txtLandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLandingActionPerformed
         }//GEN-LAST:event_txtLandingActionPerformed

    private void rbAirportLandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAirportLandingActionPerformed

        if (rbAirportLanding.isSelected()) {
            txtLanding.setEnabled(true);
            txtLanding.setBackground(whiteColor);
        } else {
            txtLanding.setEnabled(false);
            txtLanding.setBackground(blueColor);
            txtLanding.setText("");
        }    }//GEN-LAST:event_rbAirportLandingActionPerformed

    private void rbFlightIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFlightIDActionPerformed
        if (rbFlightID.isSelected()) {
            txtFlightID.setEnabled(true);
            txtFlightID.setBackground(whiteColor);
        } else {
            txtFlightID.setEnabled(false);
            txtFlightID.setBackground(blueColor);
            txtFlightID.setText("");
        }
    }//GEN-LAST:event_rbFlightIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        CreateFlightForm cff = new CreateFlightForm();
        cff.setVisible(true);
        cff.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contFindAllFlights.prepareTable();
        contFindAllFlights.SOLoadListFlights();
        contFindAllFlights.fillTable();

    }//GEN-LAST:event_formWindowOpened

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        contFindSpecificFlight.prepareTable();
        contFindSpecificFlight.SOFindSpecificFlight();
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        contFindAllFlights.prepareTable();
        contFindAllFlights.SOLoadListFlights();
        contFindAllFlights.fillTable();

        lblStatus.setForeground(Color.WHITE);
        lblStatus.setBackground(new Color(75, 181, 67));
        lblStatus.setOpaque(true);
        lblStatus.setText("All pilots are showed!");
        lblStatus.setHorizontalAlignment(SwingConstants.CENTER);
        lblStatus.setVerticalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_btnShowAllActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JPanel jPanelFilter;
    private javax.swing.JPanel jPanelFullTicket;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JRadioButton rbAirportLanding;
    private javax.swing.JRadioButton rbAirportTakeOff;
    private javax.swing.JRadioButton rbFlightID;
    private javax.swing.JTable tblFlights;
    private javax.swing.JTextField txtFlightID;
    private javax.swing.JTextField txtLanding;
    private javax.swing.JTextField txtTakeOff;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(whiteColor);
        jPanelFilter.setBackground(blueColor);
        jPanelFullTicket.setBackground(blueColor);
        jPanelUpdate.setBackground(yellowColor);
        lblNewTicket.setForeground(yellowColor);
        tblFlights.setBackground(whiteColor);
        tblFlights.setForeground(blueColor);

        lblUpdate.setForeground(whiteColor);

        txtTakeOff.setEnabled(false);
        txtTakeOff.setBackground(blueColor);
        txtTakeOff.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        txtFlightID.setEnabled(false);
        txtFlightID.setBackground(blueColor);
        txtFlightID.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        txtLanding.setEnabled(false);
        txtLanding.setBackground(blueColor);
        txtLanding.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        prepareButton();
    }

    private void prepareButton() {

        btnCreate.setBackground(whiteColor);
        btnCreate.setForeground(yellowColor);
        btnCreate.setFocusPainted(false);
        btnCreate.setFont(new Font("Sans Serif", Font.BOLD, 22));

        btnFind.setBackground(yellowColor);
        btnFind.setForeground(whiteColor);
        btnFind.setFocusPainted(false);
        btnFind.setFont(new Font("Sans Serif", Font.BOLD, 22));

        btnShowAll.setBackground(whiteColor);
        btnShowAll.setForeground(yellowColor);
        btnShowAll.setFocusPainted(false);
        btnShowAll.setFont(new Font("Sans Serif", Font.BOLD, 18));

    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Let();
    }

    @Override
    public JLabel getStatusLabel() {
        return lblStatus;
    }

    public JTextField getTxtLanding() {
        return txtLanding;
    }

    public JTextField getTxtTakeOff() {
        return txtTakeOff;
    }

    public JTextField getTxtFlightID() {
        return txtFlightID;
    }

    public JRadioButton getRbFlightID() {
        return rbFlightID;
    }

    public JRadioButton getRbAirportLanding() {
        return rbAirportLanding;
    }

    public JRadioButton getRbAirportTakeOff() {
        return rbAirportTakeOff;
    }

    public JTable getTblFlights() {
        return tblFlights;
    }

}
