/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.tickets;

import client.communication.Communication;
import client.controller.ControllerCreateTicket;
import client.controller.ControllerUpdateTicket;
import client.forme.OpstaEkranskaForma;
import domen.Karta;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Božidar
 */
public class UpdateTicketForm1 extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private final ControllerUpdateTicket contUpdateTicket;

    /**
     * Creates new form CreateTicketForm
     */
    public UpdateTicketForm1() {
        initComponents();
        contUpdateTicket = new ControllerUpdateTicket(this, new Karta());
        pripremiTabelu();
        pripremiKomboBoks();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtBrojPasosa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelFlight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbFlights = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtSeatNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTerminal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAddToTicket = new javax.swing.JButton();
        lblPriceStavka = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        cmbClass = new javax.swing.JComboBox<>();
        jPanelFullTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new javax.swing.JTable();
        lblPrice = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtIDKarte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFindID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnCreateTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addGap(578, 578, 578))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        lblNewTicket.setText("Update Ticket");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewTicket)
                .addGap(599, 599, 599))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(236, 183, 83))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel2.setText("First Name:");

        txtIme.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel3.setText("Last Name:");

        txtPrezime.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        txtBrojPasosa.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel4.setText("Passport number:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel5.setText("Ticket ID:");

        jPanelFlight.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add flight to ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(247, 184, 84))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setText("Flight:");

        cmbFlights.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel7.setText("Seat number");

        txtSeatNumber.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel8.setText("Gate:");

        txtTerminal.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel9.setText("Class:");

        btnAddToTicket.setText("Add to ticket");
        btnAddToTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTicketActionPerformed(evt);
            }
        });

        lblPriceStavka.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblPriceStavka.setText("Price:");

        txtPrice.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N

        cmbClass.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomska", "Biznis" }));

        javax.swing.GroupLayout jPanelFlightLayout = new javax.swing.GroupLayout(jPanelFlight);
        jPanelFlight.setLayout(jPanelFlightLayout);
        jPanelFlightLayout.setHorizontalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelFlightLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFlightLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFlightLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFlightLayout.createSequentialGroup()
                                .addComponent(lblPriceStavka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddToTicket)
                        .addGap(54, 54, 54))))
        );
        jPanelFlightLayout.setVerticalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPriceStavka)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddToTicket)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFullTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Full Ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(243, 187, 87))); // NOI18N

        tblTicket.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        tblTicket.setForeground(new java.awt.Color(255, 255, 255));
        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight", "Class", "Gate", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTicket.setRowHeight(35);
        jScrollPane1.setViewportView(tblTicket);
        if (tblTicket.getColumnModel().getColumnCount() > 0) {
            tblTicket.getColumnModel().getColumn(0).setResizable(false);
            tblTicket.getColumnModel().getColumn(1).setResizable(false);
            tblTicket.getColumnModel().getColumn(2).setResizable(false);
            tblTicket.getColumnModel().getColumn(3).setResizable(false);
        }

        lblPrice.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblPrice.setText("Total price:");

        txtTotalPrice.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtTotalPrice.setText("100");

        jButton1.setText("Delete ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFullTicketLayout = new javax.swing.GroupLayout(jPanelFullTicket);
        jPanelFullTicket.setLayout(jPanelFullTicketLayout);
        jPanelFullTicketLayout.setHorizontalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalPrice)
                .addGap(56, 56, 56))
        );
        jPanelFullTicketLayout.setVerticalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalPrice))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtIDKarte.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 94, 145));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Find ticket using ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(246, 183, 83))); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ticket ID:");

        txtFindID.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtFindID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFind)
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFindID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCreateTicket.setText("Update Ticket");
        btnCreateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jPanelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreateTicket)
                                .addGap(312, 312, 312))))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDKarte, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(488, 488, 488))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtIDKarte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnCreateTicket)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTicketActionPerformed
        contUpdateTicket.dodajStavkuUTabelu();

    }//GEN-LAST:event_btnAddToTicketActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTicketActionPerformed
        contUpdateTicket.SOUpdateTicket();
        dispose();
    }//GEN-LAST:event_btnCreateTicketActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        Karta k = new Karta();
        k.setSifraKarte(Integer.parseInt(txtFindID.getText()));

        contUpdateTicket.setOdo(k);
        contUpdateTicket.SOLoadTicket();

    }//GEN-LAST:event_btnFindActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contUpdateTicket.ObrisiStavku();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToTicket;
    private javax.swing.JButton btnCreateTicket;
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JComboBox cmbFlights;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFlight;
    private javax.swing.JPanel jPanelFullTicket;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceStavka;
    private javax.swing.JTable tblTicket;
    private javax.swing.JTextField txtBrojPasosa;
    private javax.swing.JTextField txtFindID;
    private javax.swing.JLabel txtIDKarte;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtTerminal;
    private javax.swing.JLabel txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(whiteColor);
        jPanelFlight.setBackground(blueColor);
        jPanelFullTicket.setBackground(blueColor);
        lblNewTicket.setForeground(yellowColor);
        tblTicket.setBackground(blueColor);
        tblTicket.setForeground(yellowColor);

        jLabel2.setForeground(whiteColor);
        jLabel3.setForeground(whiteColor);
        jLabel4.setForeground(whiteColor);
        jLabel5.setForeground(whiteColor);
        jLabel1.setForeground(whiteColor);
        jLabel9.setForeground(whiteColor);
        jLabel7.setForeground(whiteColor);
        jLabel8.setForeground(whiteColor);
        lblPriceStavka.setForeground(whiteColor);

        cmbFlights.setForeground(blueColor);
        cmbFlights.setBackground(whiteColor);

        txtBrojPasosa.setForeground(blueColor);
        txtIDKarte.setForeground(yellowColor);
        txtIme.setForeground(blueColor);
        txtPrezime.setForeground(blueColor);

        cmbFlights.setForeground(yellowColor);
        txtSeatNumber.setForeground(blueColor);
        txtTerminal.setForeground(blueColor);
        txtPrice.setForeground(blueColor);
        cmbClass.setForeground(yellowColor);

        txtTotalPrice.setForeground(yellowColor);
        lblPrice.setForeground(whiteColor);

        prepareButton();
    }

    private void prepareButton() {
        btnAddToTicket.setBackground(whiteColor);
        btnAddToTicket.setForeground(blueColor);
        btnAddToTicket.setFocusPainted(false);
        btnAddToTicket.setFont(new Font("Sans Serif", Font.BOLD, 22));

        btnCreateTicket.setBackground(yellowColor);
        btnCreateTicket.setForeground(whiteColor);
        btnCreateTicket.setFocusPainted(false);
        btnCreateTicket.setFont(new Font("Sans Serif", Font.BOLD, 26));

        btnFind.setBackground(yellowColor);
        btnFind.setForeground(whiteColor);
        btnFind.setFocusPainted(false);
        btnFind.setFont(new Font("Sans Serif", Font.BOLD, 18));

        jButton1.setBackground(yellowColor);
        jButton1.setForeground(whiteColor);
        jButton1.setFocusPainted(false);
        jButton1.setFont(new Font("Sans Serif", Font.BOLD, 18));

    }

    private void pripremiTabelu() {
        contUpdateTicket.pripremiTabelu();

    }

    private void pripremiKomboBoks() {
        contUpdateTicket.pripremiKomboBoks();
    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Karta();
    }

    @Override
    public JLabel getStatusLabel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getTxtIme() {
        return txtIme;
    }

    public JLabel getTxtIDKarte() {
        return txtIDKarte;
    }

    public JTextField getTxtPrezime() {
        return txtPrezime;
    }

    public JTextField getTxtBrojPasosa() {
        return txtBrojPasosa;
    }

    public JLabel getTxtTotalPrice() {
        return txtTotalPrice;
    }

    public javax.swing.JTable getTblTicket() {
        return tblTicket;
    }

    public JTextField getTxtPrice() {
        return txtPrice;
    }

    public JTextField getTxtTerminal() {
        return txtTerminal;
    }

    public JTextField getTxtSeatNumber() {
        return txtSeatNumber;
    }

    public JComboBox getCmbFlights() {
        return cmbFlights;
    }

    public JComboBox<String> getCmbClass() {
        return cmbClass;
    }

    public void setTxtIme(String txtIme) {
        this.txtIme.setText(txtIme);
    }

    public void setTxtPrezime(String txtPrezime) {
        this.txtPrezime.setText(txtPrezime);
    }

    public void setTxtPrice(String txtPrice) {
        this.txtPrice.setText(txtPrice);
    }

    public void setTxtBrojPasosa(String txtBrojPasosa) {
        this.txtBrojPasosa.setText(txtBrojPasosa);
    }

    public JTextField getTxtFindID() {
        return txtFindID;
    }

}
