/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.airplane;

import client.form.pilot.*;
import client.form.airport.*;
import client.form.flight.*;
import client.form.tickets.*;
import client.communication.Communication;
import client.controller.ControllerCreateAirplane;
import client.forme.OpstaEkranskaForma;
import domen.Avion;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Božidar
 */
public class CreateAirplaneForm extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private Avion avion;
    private final ControllerCreateAirplane contCreateAirplane;

    /**
     * Creates new form CreateTicketForm
     */
    public CreateAirplaneForm() {
        initComponents();
        contCreateAirplane = new ControllerCreateAirplane(this);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelTime = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtModelName = new javax.swing.JTextField();
        txtYearProduction = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelSeats = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtBussinesClass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEconomyClass = new javax.swing.JTextField();
        btnCreateFlight = new javax.swing.JButton();
        txtAirplaneID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        lblNewTicket.setText("New Airplane");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewTicket)
                .addGap(342, 342, 342))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Airplane", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel5.setText("Airplane ID:");

        jPanelTime.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(247, 184, 84))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 94, 145));
        jLabel4.setText("Model Name:");

        txtModelName.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtModelName.setForeground(new java.awt.Color(0, 94, 145));
        txtModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNameActionPerformed(evt);
            }
        });

        txtYearProduction.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtYearProduction.setForeground(new java.awt.Color(0, 94, 145));
        txtYearProduction.setText("2009");
        txtYearProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearProductionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 94, 145));
        jLabel6.setText("Year of production:");

        jPanelSeats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Seats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(236, 183, 83))); // NOI18N
        jPanelSeats.setForeground(new java.awt.Color(236, 183, 83));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bussines class:");

        txtBussinesClass.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtBussinesClass.setForeground(new java.awt.Color(0, 94, 145));
        txtBussinesClass.setText("37");
        txtBussinesClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBussinesClassActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Economy class:");

        txtEconomyClass.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        txtEconomyClass.setForeground(new java.awt.Color(0, 94, 145));
        txtEconomyClass.setText("87");
        txtEconomyClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEconomyClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeatsLayout = new javax.swing.GroupLayout(jPanelSeats);
        jPanelSeats.setLayout(jPanelSeatsLayout);
        jPanelSeatsLayout.setHorizontalGroup(
            jPanelSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBussinesClass, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEconomyClass, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelSeatsLayout.setVerticalGroup(
            jPanelSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBussinesClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEconomyClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTimeLayout = new javax.swing.GroupLayout(jPanelTime);
        jPanelTime.setLayout(jPanelTimeLayout);
        jPanelTimeLayout.setHorizontalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYearProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(jPanelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelTimeLayout.setVerticalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtYearProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnCreateFlight.setText("CREATE AIRPLANE");
        btnCreateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFlightActionPerformed(evt);
            }
        });

        txtAirplaneID.setText("111");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateFlight)
                .addGap(341, 341, 341))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(606, 606, 606)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtAirplaneID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAirplaneID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCreateFlight)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNameActionPerformed

    private void txtYearProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearProductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearProductionActionPerformed

    private void txtBussinesClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBussinesClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBussinesClassActionPerformed

    private void txtEconomyClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEconomyClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEconomyClassActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contCreateAirplane.SOFindNextIDAirplane();
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFlightActionPerformed
        contCreateAirplane.SOCreateAirplane();
        this.dispose();
    }//GEN-LAST:event_btnCreateFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateFlight;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSeats;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelTime;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JLabel txtAirplaneID;
    private javax.swing.JTextField txtBussinesClass;
    private javax.swing.JTextField txtEconomyClass;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtYearProduction;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(yellowColor);
        jPanelTime.setBackground(blueColor);
        lblNewTicket.setForeground(whiteColor);
        jPanelSeats.setBackground(blueColor);

        jLabel4.setForeground(whiteColor);
        jLabel5.setForeground(whiteColor);
        jLabel6.setForeground(whiteColor);

        txtModelName.setForeground(blueColor);
        txtAirplaneID.setForeground(yellowColor);

        prepareButton();
    }

    private void prepareButton() {

        btnCreateFlight.setBackground(whiteColor);
        btnCreateFlight.setForeground(blueColor);
        btnCreateFlight.setFocusPainted(false);
        btnCreateFlight.setFont(new Font("Sans Serif", Font.BOLD, 22));

    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Avion();
    }

    @Override
    public JLabel getStatusLabel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getTxtModelName() {
        return txtModelName;
    }

    public JLabel getTxtAirplaneID() {
        return txtAirplaneID;
    }

    public JTextField getTxtEconomyClass() {
        return txtEconomyClass;
    }

    public JTextField getTxtBussinesClass() {
        return txtBussinesClass;
    }

    public JTextField getTxtYearProduction() {
        return txtYearProduction;
    }

}
