/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.form.airplane;

import client.form.pilot.*;
import client.form.airport.*;
import client.form.flight.*;
import client.form.tickets.*;
import client.communication.Communication;
import client.controller.ControllerDeleteAirplane;
import client.controller.ControllerFindAllAirplanes;
import client.controller.ControllerFindSpecificAirplane;
import client.forme.OpstaEkranskaForma;
import domen.Avion;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Božidar
 */
public class FindAirplaneForm extends OpstaEkranskaForma {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    private final ControllerFindAllAirplanes contFindAllAirplanes;
    private final ControllerDeleteAirplane contDeleteAirplane;
    private final ControllerFindSpecificAirplane contFindSpecificAirplane;

    /**
     * Creates new form CreateTicketForm
     */
    public FindAirplaneForm() {
        initComponents();
        contFindAllAirplanes = new ControllerFindAllAirplanes(this);
        contDeleteAirplane = new ControllerDeleteAirplane(this);
        contFindSpecificAirplane = new ControllerFindSpecificAirplane(this);
        prepareForm();

        contFindAllAirplanes.prepareTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblNewTicket = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelFullTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvioni = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanelFilter = new javax.swing.JPanel();
        rbModelName = new javax.swing.JRadioButton();
        txtModelName = new javax.swing.JTextField();
        rbAirplaneID = new javax.swing.JRadioButton();
        txtAirplaneID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addGap(315, 315, 315))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNewTicket.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblNewTicket.setText("Airplane");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(lblNewTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Airplanes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(236, 183, 83))); // NOI18N

        jPanelFullTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Airplanes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(243, 187, 87))); // NOI18N

        tblAvioni.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        tblAvioni.setForeground(new java.awt.Color(255, 255, 255));
        tblAvioni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane ID ", "Model Name", "Date of Production", "Seats - Bussines class", "Seats - Economy class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAvioni.setRowHeight(35);
        jScrollPane1.setViewportView(tblAvioni);
        if (tblAvioni.getColumnModel().getColumnCount() > 0) {
            tblAvioni.getColumnModel().getColumn(0).setResizable(false);
            tblAvioni.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAvioni.getColumnModel().getColumn(1).setResizable(false);
            tblAvioni.getColumnModel().getColumn(2).setResizable(false);
            tblAvioni.getColumnModel().getColumn(3).setResizable(false);
            tblAvioni.getColumnModel().getColumn(3).setPreferredWidth(1);
            tblAvioni.getColumnModel().getColumn(4).setPreferredWidth(1);
        }

        btnCreate.setText("ADD NEW");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("SHOW ALL");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 183, 83));
        jLabel1.setText("*Selected");

        lblStatus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelFullTicketLayout = new javax.swing.GroupLayout(jPanelFullTicket);
        jPanelFullTicket.setLayout(jPanelFullTicketLayout);
        jPanelFullTicketLayout.setHorizontalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFullTicketLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(95, 95, 95))))
        );
        jPanelFullTicketLayout.setVerticalGroup(
            jPanelFullTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFullTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFullTicketLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(30, 30, 30)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(61, 61, 61))
        );

        jPanelFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Specific search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N

        rbModelName.setBackground(new java.awt.Color(0, 94, 145));
        rbModelName.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbModelName.setForeground(new java.awt.Color(236, 183, 83));
        rbModelName.setText("Model Name");
        rbModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModelNameActionPerformed(evt);
            }
        });

        txtModelName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNameActionPerformed(evt);
            }
        });

        rbAirplaneID.setBackground(new java.awt.Color(0, 94, 145));
        rbAirplaneID.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        rbAirplaneID.setForeground(new java.awt.Color(236, 183, 83));
        rbAirplaneID.setText("Airplane ID");
        rbAirplaneID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAirplaneIDActionPerformed(evt);
            }
        });

        txtAirplaneID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilterLayout = new javax.swing.GroupLayout(jPanelFilter);
        jPanelFilter.setLayout(jPanelFilterLayout);
        jPanelFilterLayout.setHorizontalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelName)
                    .addComponent(rbModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAirplaneID)
                    .addComponent(rbAirplaneID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFind)
                .addGap(75, 75, 75))
        );
        jPanelFilterLayout.setVerticalGroup(
            jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilterLayout.createSequentialGroup()
                .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFilterLayout.createSequentialGroup()
                                .addComponent(rbModelName)
                                .addGap(18, 18, 18)
                                .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFilterLayout.createSequentialGroup()
                                .addComponent(rbAirplaneID)
                                .addGap(18, 18, 18)
                                .addComponent(txtAirplaneID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFilterLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnFind)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFullTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNameActionPerformed
         }//GEN-LAST:event_txtModelNameActionPerformed

    private void rbModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModelNameActionPerformed

        if (rbModelName.isSelected()) {
            txtModelName.setEnabled(true);
            txtModelName.setBackground(whiteColor);
        } else {
            txtModelName.setEnabled(false);
            txtModelName.setBackground(blueColor);
            txtModelName.setText("");
        }    }//GEN-LAST:event_rbModelNameActionPerformed

    private void rbAirplaneIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAirplaneIDActionPerformed
        if (rbAirplaneID.isSelected()) {
            txtAirplaneID.setEnabled(true);
            txtAirplaneID.setBackground(whiteColor);
        } else {
            txtAirplaneID.setEnabled(false);
            txtAirplaneID.setBackground(blueColor);
            txtAirplaneID.setText("");
        }
    }//GEN-LAST:event_rbAirplaneIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        CreateAirplaneForm caf = new CreateAirplaneForm();
        caf.setVisible(true);
        caf.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contFindAllAirplanes.SOLoadListAirplanes();
        contFindAllAirplanes.fillTable();
    }//GEN-LAST:event_formWindowOpened

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        contFindSpecificAirplane.prepareTable();
        contFindSpecificAirplane.SOFindSpecificAirplane();
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!tblAvioni.getSelectionModel().isSelectionEmpty()) {

            int input = JOptionPane.showConfirmDialog(null,
                    "Do you want to proceed to delete this airplane?", "Select an Option...", JOptionPane.YES_NO_OPTION);

            if (input == 0) {
                contDeleteAirplane.SODeleteAirplane();
                contFindSpecificAirplane.prepareTable();
                contFindAllAirplanes.SOLoadListAirplanes();
                contFindAllAirplanes.fillTable();
            } else {
                return;
            }
        } else {
            lblStatus.setForeground(Color.WHITE);
            lblStatus.setBackground(new Color(219, 31, 31));
            lblStatus.setOpaque(true);
            lblStatus.setText("You didnt select any row!");
            lblStatus.setHorizontalAlignment(SwingConstants.CENTER);
            lblStatus.setVerticalAlignment(SwingConstants.CENTER);

        }    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        contFindSpecificAirplane.prepareTable();
        contFindAllAirplanes.SOLoadListAirplanes();
        contFindAllAirplanes.fillTable();

        lblStatus.setForeground(Color.WHITE);
        lblStatus.setBackground(new Color(75, 181, 67));
        lblStatus.setOpaque(true);
        lblStatus.setText("All airplanes are showed!");
        lblStatus.setHorizontalAlignment(SwingConstants.CENTER);
        lblStatus.setVerticalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFilter;
    private javax.swing.JPanel jPanelFullTicket;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNewTicket;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rbAirplaneID;
    private javax.swing.JRadioButton rbModelName;
    private javax.swing.JTable tblAvioni;
    private javax.swing.JTextField txtAirplaneID;
    private javax.swing.JTextField txtModelName;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        getContentPane().setBackground(blueColor);

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelMain.setBackground(blueColor);
        jPanelTicket.setBackground(whiteColor);
        jPanelFilter.setBackground(blueColor);
        jPanelFullTicket.setBackground(blueColor);
        lblNewTicket.setForeground(yellowColor);
        tblAvioni.setBackground(whiteColor);
        tblAvioni.setForeground(yellowColor);

        txtAirplaneID.setEnabled(false);
        txtAirplaneID.setBackground(blueColor);
        txtAirplaneID.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        txtModelName.setEnabled(false);
        txtModelName.setBackground(blueColor);
        txtModelName.setBorder(new CompoundBorder(new EmptyBorder(1, 1, 1, 1), new LineBorder(blueColor, 2)));

        prepareButton();
    }

    private void prepareButton() {

        btnCreate.setBackground(whiteColor);
        btnCreate.setForeground(blueColor);
        btnCreate.setFocusPainted(false);
        btnCreate.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnDelete.setBackground(whiteColor);
        btnDelete.setForeground(blueColor);
        btnDelete.setFocusPainted(false);
        btnDelete.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnUpdate.setBackground(whiteColor);
        btnUpdate.setForeground(blueColor);
        btnUpdate.setFocusPainted(false);
        btnUpdate.setFont(new Font("Sans Serif", Font.BOLD, 18));

        btnFind.setBackground(yellowColor);
        btnFind.setForeground(whiteColor);
        btnFind.setFocusPainted(false);
        btnFind.setFont(new Font("Sans Serif", Font.BOLD, 22));

    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return new Avion();
    }

    @Override
    public JLabel getStatusLabel() {
        return lblStatus;
    }

    public JTable getTblAvioni() {
        return tblAvioni;
    }

    public JTextField getTxtModelName() {
        return txtModelName;
    }

    public JTextField getTxtAirplaneID() {
        return txtAirplaneID;
    }

    public JRadioButton getRbModelName() {
        return rbModelName;
    }

    public JRadioButton getRbAirplaneID() {
        return rbAirplaneID;
    }

}
