/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.forme;

import client.communication.Communication;
import client.form.airplane.FindAirplaneForm;
import client.form.airport.FindAirportForm;
import client.form.flight.CreateFlightForm;
import client.form.flight.FindFlightForm;
import client.form.pilot.FindPilotForm;
import client.form.tickets.CreateTicketForm;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Božidar
 */
public class MainForm extends javax.swing.JFrame {

    Color whiteColor = Color.WHITE;
    Color blueColor = new Color(0, 94, 145);
    Color lightBlueColor = new Color(0, 104, 145);
    Color succesColor = new Color(75, 181, 67);
    Color errorColor = new Color(219, 31, 31);
    Color yellowColor = new Color(236, 183, 83);

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGlavni = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        lblTickets = new javax.swing.JLabel();
        btnTickets = new javax.swing.JButton();
        jPanelFlights = new javax.swing.JPanel();
        lblFlights = new javax.swing.JLabel();
        btnFligths = new javax.swing.JButton();
        jPanelAAP = new javax.swing.JPanel();
        btnAirport = new javax.swing.JButton();
        btnAirplanes = new javax.swing.JButton();
        btnPilots = new javax.swing.JButton();
        jPanelNaslov = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");

        jPanelGlavni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome aboard,", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        lblIme.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblIme.setText("Bozidar");

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jPanelTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticket", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 26), new java.awt.Color(236, 183, 83))); // NOI18N

        lblTickets.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        lblTickets.setText("Create new tickets or update existing");

        btnTickets.setText("Tickets");
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTickets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTickets))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelFlights.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flights", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 26), new java.awt.Color(243, 183, 83))); // NOI18N

        lblFlights.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        lblFlights.setText("Create new flights or find specific");

        btnFligths.setText("Flights");
        btnFligths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFligthsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFlightsLayout = new javax.swing.GroupLayout(jPanelFlights);
        jPanelFlights.setLayout(jPanelFlightsLayout);
        jPanelFlightsLayout.setHorizontalGroup(
            jPanelFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblFlights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFligths, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFlightsLayout.setVerticalGroup(
            jPanelFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFligths, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlights))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelAAP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Airports, Airplanes and Pilots", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 26), new java.awt.Color(243, 183, 83))); // NOI18N

        btnAirport.setText("Airports");
        btnAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportActionPerformed(evt);
            }
        });

        btnAirplanes.setText("Airplanes");
        btnAirplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirplanesActionPerformed(evt);
            }
        });

        btnPilots.setText("Pilots");
        btnPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAAPLayout = new javax.swing.GroupLayout(jPanelAAP);
        jPanelAAP.setLayout(jPanelAAPLayout);
        jPanelAAPLayout.setHorizontalGroup(
            jPanelAAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAAPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAirplanes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelAAPLayout.setVerticalGroup(
            jPanelAAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAAPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelAAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAirplanes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGlavniLayout = new javax.swing.GroupLayout(jPanelGlavni);
        jPanelGlavni.setLayout(jPanelGlavniLayout);
        jPanelGlavniLayout.setHorizontalGroup(
            jPanelGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlavniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGlavniLayout.createSequentialGroup()
                        .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGlavniLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanelGlavniLayout.createSequentialGroup()
                        .addGroup(jPanelGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelFlights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanelGlavniLayout.setVerticalGroup(
            jPanelGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlavniLayout.createSequentialGroup()
                .addGroup(jPanelGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIme)
                    .addComponent(btnLogOut))
                .addGap(61, 61, 61)
                .addComponent(jPanelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanelFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanelAAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNaslov.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNaslov.setText("PS AIRWAYS");

        javax.swing.GroupLayout jPanelNaslovLayout = new javax.swing.GroupLayout(jPanelNaslov);
        jPanelNaslov.setLayout(jPanelNaslovLayout);
        jPanelNaslovLayout.setHorizontalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addGap(234, 234, 234))
        );
        jPanelNaslovLayout.setVerticalGroup(
            jPanelNaslovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNaslovLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNaslov)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanelGlavni, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed

        CreateTicketForm ctf = new CreateTicketForm();
        ctf.setVisible(true);
        ctf.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnFligthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFligthsActionPerformed
        FindFlightForm cff = new FindFlightForm();
        cff.setVisible(true);
        cff.setLocationRelativeTo(null);    }//GEN-LAST:event_btnFligthsActionPerformed

    private void btnAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportActionPerformed
        FindAirportForm faf = new FindAirportForm();
        faf.setVisible(true);
        faf.setLocationRelativeTo(null);    }//GEN-LAST:event_btnAirportActionPerformed

    private void btnPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilotsActionPerformed
        FindPilotForm fpf = new FindPilotForm();
        fpf.setVisible(true);
        fpf.setLocationRelativeTo(null);     }//GEN-LAST:event_btnPilotsActionPerformed

    private void btnAirplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirplanesActionPerformed
        FindAirplaneForm faf = new FindAirplaneForm();
        faf.setVisible(true);
        faf.setLocationRelativeTo(null);     }//GEN-LAST:event_btnAirplanesActionPerformed

    private void prepareForm() {
        getContentPane().setBackground(blueColor);
        jPanelGlavni.setBackground(blueColor);
        lblIme.setForeground(yellowColor);
        lblIme.setText(Communication.getInstanca().getTrenutniKorisnik().toString());

        jPanelNaslov.setBackground(yellowColor);
        lblNaslov.setForeground(whiteColor);

        jPanelFlights.setBackground(blueColor);
        jPanelTicket.setBackground(blueColor);
        jPanelAAP.setBackground(blueColor);

        lblTickets.setForeground(whiteColor);
        lblFlights.setForeground(whiteColor);

        prepareButton();
    }

    private void prepareButton() {
        btnLogOut.setBackground(yellowColor);
        btnLogOut.setForeground(whiteColor);
        btnLogOut.setFocusPainted(false);
        btnLogOut.setFont(new Font("Sans Serif", Font.BOLD, 22));

        btnTickets.setBackground(whiteColor);
        btnTickets.setForeground(blueColor);
        btnTickets.setFocusPainted(false);
        btnTickets.setFont(new Font("Sans Serif", Font.BOLD, 24));

        btnFligths.setBackground(whiteColor);
        btnFligths.setForeground(blueColor);
        btnFligths.setFocusPainted(false);
        btnFligths.setFont(new Font("Sans Serif", Font.BOLD, 24));

        btnAirplanes.setBackground(whiteColor);
        btnAirplanes.setForeground(blueColor);
        btnAirplanes.setFocusPainted(false);
        btnAirplanes.setFont(new Font("Sans Serif", Font.BOLD, 24));

        btnAirport.setBackground(whiteColor);
        btnAirport.setForeground(blueColor);
        btnAirport.setFocusPainted(false);
        btnAirport.setFont(new Font("Sans Serif", Font.BOLD, 24));

        btnPilots.setBackground(whiteColor);
        btnPilots.setForeground(blueColor);
        btnPilots.setFocusPainted(false);
        btnPilots.setFont(new Font("Sans Serif", Font.BOLD, 24));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirplanes;
    private javax.swing.JButton btnAirport;
    private javax.swing.JButton btnFligths;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPilots;
    private javax.swing.JButton btnTickets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAAP;
    private javax.swing.JPanel jPanelFlights;
    private javax.swing.JPanel jPanelGlavni;
    private javax.swing.JPanel jPanelNaslov;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JLabel lblFlights;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblTickets;
    // End of variables declaration//GEN-END:variables
}
